# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('manager', '0003_auto_20170315_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='registered_course', to='courses.Course'),
        ),
    ]
