# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_student_courses'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(null=True, related_name='registered_students', to='manager.Student'),
        ),
    ]
