# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_student_courses'),
        ('courses', '0002_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(null=True, related_name='courses', to='manager.Student'),
        ),
    ]
